### ISSUE TITLE
LotFrontage feature imputation using advanced algorithms like random forest, gradient bossting instead of linear regression

### ISSUE THREAD

**Issue by tarun-goyal** [tarun-goyal/House-Prices#10]
@Gaurav-Sachdeva 
I forgot to mention it earlier. You may want to use some more advanced algorithms to impute the missing values of LotFrontage. Linear Regression does the required job but accuracy might not be that good.

**Comment by tarun-goyal** [comment]
@Gaurav-Sachdeva 
Just noticed you made a submission to House Prices as well. Sorry, I left you just 1 submission for today. From now on, let us decide in advance if one is going to make some submissions and we can plan accordingly.

**Comment by Gaurav-Sachdeva** [comment]
@tarun-goyal 
No problem..I can submit it tomorrow.

**Comment by tarun-goyal** [comment]
Closed via #13
