### ISSUE TITLE
Correction: Few continuous variables are getting treated as categorical

### ISSUE THREAD

**Issue by Gaurav-Sachdeva** [tarun-goyal/House-Prices#11]

**Comment by tarun-goyal** [comment]
@Gaurav-Sachdeva 
Only two continuous features are getting converted into categorical type: `MasVnrArea` and `GarageYrBlt`. These are among the ones which were being imputed. Fixing `GarageYrBlt` might not help us in improving model predictions but `MasVnrArea` seems like an important feature for the house prices: [https://en.wikipedia.org/wiki/Masonry_veneer](url)

**Comment by tarun-goyal** [comment]
Closed via #13
