### ISSUE TITLE
Outlier Treatment

### ISSUE THREAD

**Issue by Gaurav-Sachdeva** [tarun-goyal/House-Prices#14]

**Comment by tarun-goyal** [comment]
@Gaurav-Sachdeva 
I tried filtering out some data randomly....no logic involved:
1. Filtering out house prices > 550000 (7 data points)
2. Filtering out house prices > 700000 (2 data points)

Cross-validated test RMSE did improve for both these iterations, but not on public scorecard (50% test data). The second iteration's test RMSE was lower than the first one.

Please check at your end as well if we could improve anything here, obviously with some logic :)

**Comment by tarun-goyal** [comment]
Closes via #15
