### ISSUE TITLE
Conversion of numeric data type Categorical features into string/object

### ISSUE THREAD

**Issue by tarun-goyal** [tarun-goyal/House-Prices#8]

**Comment by tarun-goyal** [comment]
@Gaurav-Sachdeva 
I converted the discussed features into categorical objects. But did not find any improvement in the test rmse over earlier models. Please have a look at all features and let me know if any other feature(s) should be included/excluded for categorical conversion apart from this list. Following are the features I converted: `['OverallQual', 'OverallCond', 'BsmtFullBath',
                       'BsmtHalfBath',	'FullBath',	'HalfBath', 'MoSold',
                       'YrSold', 'BedroomAbvGr', 'KitchenAbvGr',
                       'TotRmsAbvGrd', 'GarageCars', 'Fireplaces']`.

**Comment by Gaurav-Sachdeva** [comment]
I think we can exclude `'OverallQual', 'OverallCond',`. Price is likely to be a monotonic function of these variables. 
I think the above list covers all possible columns that could be considered categorical.

**Comment by tarun-goyal** [comment]
Closing via #13
